### ISSUE TITLE
MedTagger component not installing correctly

### ISSUE THREAD

**Issue by etfrenchvcu** [OHNLP/Backbone#2]
I am trying to run the [run_nlp]_[ohdsi_cdm]_[ohdsi_cdm] script for extracting covid-19 concepts from clinical notes for N3C. I have downloaded the latest releases of Backbone and MedTagger. I was able to successfully run MedTagger as a standalone application, but am having trouble integrating it as a component into Backbone. I am able to run package_modules_and_configs.bat successfully to created packaged jar files, but when I run run_pipeline_local.bat, I get the following error:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.simontuffs.onejar.Boot.run(Boot.java:313)
        at com.simontuffs.onejar.Boot.main(Boot.java:161)
Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `java.lang.Class`, problem: org.ohnlp.medtagger.backbone.MedTaggerBackboneTransform
 at [Source: (sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream); line: 17, column: 16] (through reference chain: org.ohnlp.backbone.core.config.BackboneConfiguration["pipeline"]->java.util.ArrayList[1]->org.ohnlp.backbone.core.config.BackbonePipelineComponentConfiguration["clazz"])
        at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
        at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1732)
        at com.fasterxml.jackson.databind.DeserializationContext.handleInstantiationProblem(DeserializationContext.java:1106)
        at com.fasterxml.jackson.databind.deser.std.FromStringDeserializer$Std._deserialize(FromStringDeserializer.java:245)
        at com.fasterxml.jackson.databind.deser.std.FromStringDeserializer.deserialize(FromStringDeserializer.java:145)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3242)
        at org.ohnlp.backbone.core.BackboneRunner.main(BackboneRunner.java:25)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.ohnlp.medtagger.backbone.MedTaggerBackboneTransform
        at com.simontuffs.onejar.JarClassLoader.findClass(JarClassLoader.java:694)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at com.simontuffs.onejar.JarClassLoader.loadClass(JarClassLoader.java:611)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at com.fasterxml.jackson.databind.type.TypeFactory.classForName(TypeFactory.java:329)
        at com.fasterxml.jackson.databind.type.TypeFactory.findClass(TypeFactory.java:311)
        at com.fasterxml.jackson.databind.DeserializationContext.findClass(DeserializationContext.java:556)
        at com.fasterxml.jackson.databind.deser.std.FromStringDeserializer$Std._deserialize(FromStringDeserializer.java:243)
        ... 19 more
```

It seems like the program is not able to integrate the MedTagger component into the pipeline, but it's hard to say for sure without manually debugging the Java code, which I was hoping to avoid. I "installed" the MedTagger component by unzipping the latest release in the modules directory so that my file structure looks like this:

BACKBONE_ROOT
--bin
--configs
--modules
----MedTagger
...

I ran package_modules_and_configs.bat after all changes to the modules directory and config files. Are there additional steps I ought to be taking to "install" MedTagger? 
I am running the program locally on a Windows 10 machine.

**Comment by etfrenchvcu** [comment]
I was able to resolve the issue. The problem was that only the MedTagger .jar file should be placed in the modules directory, not the entire repository. Also, you will need to copy the MedTagger\medtaggerieresources\covid19 directory (from the MedTagger repo) into BACKBONE_ROOT/resources.
